import { useState } from 'react';
import { Alert, Button, Form, Input, Modal, Select, Space, Switch, Table, Tag } from 'antd';
import { Link } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api, labels, ProviderState, time } from './api';
import { Metric, PageTitle, QueryError } from './ui';

type QualityData={today_matches:number;matched:number;review:number;unmatched:number;rejected:number;last_sync_at:string|null;sync_success_rate:number|null;sync_runs_24h:number;recent_errors:{id:string;provider:string;operation:string;error_code:string;at:string}[];demo_mode:boolean};
const stateTag=(status:string)=><Tag color={status==='HEALTHY'||status==='SUCCESS'?'green':status==='DOWN'||status==='FAILED'?'red':status==='DEGRADED'||status==='EMPTY'?'gold':'default'}>{status}</Tag>;

export function Quality(){
 const quality=useQuery({queryKey:['quality'],queryFn:()=>api<QualityData>('/quality'),refetchInterval:30000});
 const providers=useQuery({queryKey:['providers'],queryFn:()=>api<ProviderState[]>('/providers/status'),refetchInterval:30000});
 const q=quality.data;
 return <><PageTitle eyebrow="DATA QUALITY" title="数据质量中心" description="了解覆盖情况、映射缺口与采集异常。"/><QueryError error={quality.error}/>{q?.demo_mode&&<Alert type="warning" message="当前为 Mock 演示环境。真实供应商的可用性需单独验收。"/>}<div className="metrics"><Metric label="今天体彩比赛" value={q?.today_matches??'—'} detail="按北京时间销售日"/><Metric label="已确认映射" value={q?.matched??'—'} detail="全部存量供应商比赛"/><Metric label="待人工审核" value={q?.review??'—'} detail="低置信度或身份已变更"/><Metric label="未映射" value={q?.unmatched??'—'} detail="保留 Raw，等待身份确认"/></div><div className="detail-grid"><div className="panel content-pad"><h3>同步概况</h3><DescriptionsLine label="24 小时同步成功率" value={q?.sync_success_rate==null?'暂无同步':`${(q.sync_success_rate*100).toFixed(1)}%`}/><DescriptionsLine label="已结束同步次数" value={q?.sync_runs_24h??0}/><DescriptionsLine label="最近成功同步" value={time(q?.last_sync_at??null,true)}/><DescriptionsLine label="已拒绝映射" value={q?.rejected??0}/><Link to="/mappings"><Button className="section-gap">处理映射缺口</Button></Link></div><div className="panel content-pad"><h3>Provider 健康</h3>{providers.data?.map(p=><div className="description-line" key={p.provider}><span>{labels[p.provider]??p.provider}</span>{stateTag(p.status)}</div>)}<QueryError error={providers.error}/></div></div><div className="panel section-gap"><div className="panel-toolbar"><strong>最近错误</strong><Link to="/jobs">查看同步任务 →</Link></div><Table rowKey="id" dataSource={q?.recent_errors} pagination={false} columns={[{title:'数据源',dataIndex:'provider',render:v=>labels[v]??v},{title:'操作',dataIndex:'operation'},{title:'错误代码',dataIndex:'error_code',render:v=><Tag color="red">{v}</Tag>},{title:'发生时间',dataIndex:'at',render:v=>time(v,true)}]}/></div></>;
}
function DescriptionsLine({label,value}:{label:string;value:React.ReactNode}){return <div className="description-line"><span>{label}</span><strong>{value}</strong></div>}

export function Providers(){
 const query=useQuery({queryKey:['providers'],queryFn:()=>api<ProviderState[]>('/providers/status'),refetchInterval:15000});
 const [editing,setEditing]=useState<ProviderState|null>(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 async function save(){if(!editing)return;setSaving(true);try{await api(`/admin/providers/${editing.provider}`,{method:'PATCH',body:JSON.stringify({enabled:!editing.enabled,reason})});setEditing(null);await query.refetch()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <><PageTitle eyebrow="PROVIDERS" title="数据源管理" description="查看连接健康与限流状态，控制已配置的采集源。"/><QueryError error={query.error}/><Alert type="info" message="API Key 和数据源地址通过本地 .env 配置。页面只管理启用状态，不展示密钥。"/><div className="panel"><Table<ProviderState> rowKey="provider" dataSource={query.data} loading={query.isLoading} pagination={false} scroll={{x:950}} columns={[
 {title:'Provider',dataIndex:'provider',render:v=><strong>{labels[v]??v}</strong>},{title:'状态',dataIndex:'status',render:stateTag},{title:'最近成功',dataIndex:'last_success_at',render:v=>time(v,true)},{title:'最近失败',dataIndex:'last_failure_at',render:v=>time(v,true)},{title:'耗时',dataIndex:'latency',render:v=>v==null?'—':`${v} ms`},{title:'连续失败',dataIndex:'consecutive_failures'},{title:'限流',dataIndex:'rate_limit_status'},{title:'管理',render:(_,p)=><Button size="small" onClick={()=>{setEditing(p);setReason('');setError('')}}>{p.enabled?'禁用':'启用'}</Button>}]}/></div><Modal title={`${editing?.enabled?'禁用':'启用'} ${editing?.provider}`} open={!!editing} onCancel={()=>setEditing(null)} onOk={()=>void save()} okButtonProps={{disabled:reason.length<3}} confirmLoading={saving}>{error&&<Alert type="error" message={error}/>}<Input.TextArea aria-label="变更原因" placeholder="请输入变更原因（至少 3 个字符）" value={reason} onChange={e=>setReason(e.target.value)}/></Modal></>;
}

type SyncRun={id:string;provider:string;operation:string;status:string;started_at:string;finished_at:string|null;duration_ms:number|null;records:number;error_code:string|null;error_message:string|null;raw_payload_id:string|null;request_id:string};
export function Jobs(){
 const [page,setPage]=useState(1),[provider,setProvider]=useState('sporttery'),[operation,setOperation]=useState('matches'),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[raw,setRaw]=useState<unknown>(null);
 const query=useQuery({queryKey:['jobs',page],queryFn:()=>api<{items:SyncRun[];total:number}>(`/admin/sync-runs?page=${page}`),refetchInterval:5000,retry:false});
 const sources=useQuery({queryKey:['providers'],queryFn:()=>api<ProviderState[]>('/providers/status')});
 async function run(){setBusy(true);setError('');try{const result=await api<{status:string;id:string}>('/admin/sync',{method:'POST',body:JSON.stringify({provider,operation})});setNotice(`同步已排队：${result.id}`);await query.refetch()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function showRaw(id:string){try{setRaw(await api(`/admin/raw/${id}`))}catch(e){setError((e as Error).message)}}
 return <><PageTitle eyebrow="INGESTION JOBS" title="同步任务" description="查看每一次采集结果，并追溯到原始响应。"/>{notice&&<Alert type="success" message={notice}/>} {error&&<Alert type="error" message={error}/>}<QueryError error={query.error}/><div className="panel"><div className="panel-toolbar"><strong>采集记录</strong><Space wrap><Select value={provider} onChange={setProvider} style={{minWidth:150}} options={sources.data?.filter(p=>p.enabled).map(p=>({value:p.provider,label:labels[p.provider]??p.provider}))}/><Select value={operation} onChange={setOperation} options={[{value:'matches',label:'比赛与映射'},{value:'odds',label:'赔率采集'}]}/><Button type="primary" loading={busy} onClick={()=>void run()}>立即同步</Button></Space></div><Table<SyncRun> rowKey="id" dataSource={query.data?.items} pagination={{current:page,pageSize:30,total:query.data?.total,onChange:setPage,showSizeChanger:false}} scroll={{x:1000}} expandable={{expandedRowRender:r=><pre className="json-block">{JSON.stringify({request_id:r.request_id,error_code:r.error_code,error_message:r.error_message,finished_at:r.finished_at},null,2)}</pre>}} columns={[{title:'Provider',dataIndex:'provider'},{title:'操作',dataIndex:'operation'},{title:'状态',dataIndex:'status',render:stateTag},{title:'记录处理数',dataIndex:'records'},{title:'启动时间',dataIndex:'started_at',render:v=>time(v,true)},{title:'耗时',dataIndex:'duration_ms',render:v=>v==null?'—':`${v}ms`},{title:'原始响应',render:(_,r)=>r.raw_payload_id?<Button size="small" onClick={()=>void showRaw(r.raw_payload_id!)}>查看 Raw</Button>:'—'}]}/></div><Modal title="原始数据与来源" open={raw!==null} onCancel={()=>setRaw(null)} footer={null} width={850}><pre className="json-block">{JSON.stringify(raw,null,2)}</pre></Modal></>;
}

type User={id:string;email:string;role:string;active:boolean;created_at:string};
export function Users(){
 const [page,setPage]=useState(1),[editing,setEditing]=useState<User|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);const [form]=Form.useForm();
 const query=useQuery({queryKey:['users',page],queryFn:()=>api<{items:User[];total:number}>(`/admin/users?page=${page}`),retry:false});
 async function save(){if(!editing)return;const values=await form.validateFields();setSaving(true);try{await api(`/admin/users/${editing.id}`,{method:'PATCH',body:JSON.stringify(values)});setEditing(null);await query.refetch()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <><PageTitle eyebrow="ACCESS CONTROL" title="用户管理" description="按角色授予访问权限，所有变更进入审计记录。"/><QueryError error={query.error}/><div className="panel"><Table<User> rowKey="id" dataSource={query.data?.items} pagination={{current:page,pageSize:30,total:query.data?.total,onChange:setPage,showSizeChanger:false}} columns={[{title:'邮箱',dataIndex:'email'},{title:'角色',dataIndex:'role',render:v=><Tag>{v}</Tag>},{title:'状态',dataIndex:'active',render:v=>v?'启用':'禁用'},{title:'注册时间',dataIndex:'created_at',render:v=>time(v,true)},{title:'管理',render:(_,u)=><Button size="small" onClick={()=>{setEditing(u);setError('');form.setFieldsValue({...u,reason:''})}}>编辑权限</Button>}]}/></div><Modal title="修改用户权限" open={!!editing} onCancel={()=>setEditing(null)} onOk={()=>void save()} confirmLoading={saving}>{error&&<Alert type="error" message={error}/>}<Form form={form} layout="vertical"><Form.Item name="role" label="角色"><Select options={['ADMIN','ANALYST','USER'].map(v=>({value:v,label:v}))}/></Form.Item><Form.Item name="active" label="启用账户" valuePropName="checked"><Switch/></Form.Item><Form.Item name="reason" label="变更原因" rules={[{required:true,min:3}]}><Input.TextArea/></Form.Item></Form></Modal></>;
}

type Audit={id:string;operation:string;entity_type:string;entity_id:string;actor_id:string|null;before:unknown;after:unknown;reason:string|null;created_at:string;request_id:string|null};
export function Logs(){
 const [page,setPage]=useState(1);const query=useQuery({queryKey:['logs',page],queryFn:()=>api<{items:Audit[];total:number}>(`/admin/logs?page=${page}`),retry:false});
 return <><PageTitle eyebrow="AUDIT TRAIL" title="审计日志" description="实体、映射与管理操作的不可变记录。"/><QueryError error={query.error}/><div className="panel"><Table<Audit> rowKey="id" dataSource={query.data?.items} pagination={{current:page,pageSize:30,total:query.data?.total,onChange:setPage,showSizeChanger:false}} scroll={{x:950}} expandable={{expandedRowRender:r=><pre className="json-block">{JSON.stringify({entity_id:r.entity_id,actor_id:r.actor_id,request_id:r.request_id,before:r.before,after:r.after},null,2)}</pre>}} columns={[{title:'操作',dataIndex:'operation',render:v=><Tag>{v}</Tag>},{title:'实体类型',dataIndex:'entity_type'},{title:'理由',dataIndex:'reason',render:v=>v??'系统记录'},{title:'操作时间',dataIndex:'created_at',render:v=>time(v,true)}]}/></div><p className="muted small-copy">采集错误请查看同步任务。HTTP 结构化运行日志由后端标准输出提供。</p></>;
}
