import React from 'react';
import ReactDOM from 'react-dom/client';
import { ConfigProvider } from 'antd';
import zhCN from 'antd/locale/zh_CN';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import './style.css';
const client=new QueryClient();
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><ConfigProvider locale={zhCN} theme={{token:{colorPrimary:'#18654a',borderRadius:10,fontFamily:'Inter, "Microsoft YaHei", sans-serif'}}}><QueryClientProvider client={client}><BrowserRouter><App/></BrowserRouter></QueryClientProvider></ConfigProvider></React.StrictMode>);
