"""odds observations

Revision ID: 549daf86d8c7
Revises: 002_immutable
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '549daf86d8c7'
down_revision = '002_immutable'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odds_observations',
    sa.Column('odds_snapshot_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('raw_payload_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['odds_snapshot_id'], ['odds_snapshots.id'], ),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['provider_raw_payloads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odds_snapshot_id', 'raw_payload_id')
    )
    with op.batch_alter_table('odds_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odds_observations_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_observations_odds_snapshot_id'), ['odds_snapshot_id'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odds_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odds_observations_odds_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_odds_observations_collected_at'))

    op.drop_table('odds_observations')
    # ### end Alembic commands ###

