"""initial data foundation

Revision ID: f20024045a94
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql
revision = 'f20024045a94'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_operation'), ['operation'], unique=False)

    op.create_table('competitions',
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_raw_payloads',
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('mock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_raw_payloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_raw_payloads_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_raw_payloads_payload_hash'), ['payload_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_raw_payloads_provider'), ['provider'], unique=False)

    op.create_table('provider_states',
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('rate_limit_status', sa.String(length=60), nullable=False),
    sa.Column('next_allowed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('teams',
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('name_zh', sa.String(length=200), nullable=True),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'ANALYST', 'USER')", name='valid_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competition_identities',
    sa.Column('competition_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id')
    )
    op.create_table('matches',
    sa.Column('sporttery_match_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('match_num', sa.String(length=40), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('sell_date', sa.Date(), nullable=False),
    sa.Column('competition_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('competition_name', sa.String(length=200), nullable=False),
    sa.Column('competition_code', sa.String(length=100), nullable=True),
    sa.Column('home_team_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('away_team_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('home_team_name', sa.String(length=200), nullable=False),
    sa.Column('away_team_name', sa.String(length=200), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_timezone', sa.String(length=60), nullable=True),
    sa.Column('source_timezone', sa.String(length=60), nullable=False),
    sa.Column('sell_status', sa.String(length=30), nullable=False),
    sa.Column('single_allowed', sa.Boolean(), nullable=True),
    sa.Column('markets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw_payload_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('mock', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source = 'sporttery'", name='sporttery_only'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['provider_raw_payloads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sporttery_match_id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_kickoff_at'), ['kickoff_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_sell_date'), ['sell_date'], unique=False)

    op.create_table('provider_matches',
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('provider_match_id', sa.String(length=200), nullable=False),
    sa.Column('home_provider_team_id', sa.String(length=200), nullable=True),
    sa.Column('away_provider_team_id', sa.String(length=200), nullable=True),
    sa.Column('home_name', sa.String(length=200), nullable=False),
    sa.Column('away_name', sa.String(length=200), nullable=False),
    sa.Column('competition', sa.String(length=200), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['provider_raw_payloads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_match_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('sync_runs',
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_payload_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['provider_raw_payloads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_provider'), ['provider'], unique=False)

    op.create_table('team_aliases',
    sa.Column('team_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('external_team_id', sa.String(length=200), nullable=True),
    sa.Column('alias_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('mapping_source', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_team_id', 'normalized_name')
    )
    with op.batch_alter_table('team_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_aliases_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_aliases_team_id'), ['team_id'], unique=False)

    op.create_table('team_identities',
    sa.Column('team_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('external_team_id', sa.String(length=200), nullable=False),
    sa.Column('mapping_source', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_team_id')
    )
    op.create_table('match_mapping',
    sa.Column('provider_match_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('match_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('match_method', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('candidates', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 100', name='valid_confidence'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['provider_match_id'], ['provider_matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_match_id')
    )
    with op.batch_alter_table('match_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_mapping_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_mapping_status'), ['status'], unique=False)

    op.create_table('match_versions',
    sa.Column('match_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('raw_payload_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['provider_raw_payloads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_versions_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_versions_match_id'), ['match_id'], unique=False)

    op.create_table('odds_snapshots',
    sa.Column('match_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('bookmaker', sa.String(length=60), nullable=False),
    sa.Column('market_type', sa.String(length=40), nullable=False),
    sa.Column('selection', sa.String(length=60), nullable=False),
    sa.Column('line', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('raw_odds', sa.String(length=80), nullable=False),
    sa.Column('decimal_odds', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('implied_probability', sa.Numeric(precision=16, scale=12), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('raw_payload_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('mapping_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('mapping_version', sa.Integer(), nullable=True),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('mock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('decimal_odds > 1', name='valid_decimal_odds'),
    sa.CheckConstraint('implied_probability > 0 AND implied_probability < 1', name='valid_probability'),
    sa.ForeignKeyConstraint(['mapping_id'], ['match_mapping.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['provider_raw_payloads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_odds_cutoff', ['match_id', 'collected_at', 'created_at'], unique=False)
        batch_op.create_index('ix_odds_series', ['match_id', 'provider', 'market_type', 'collected_at'], unique=False)

    op.create_table('odds_key_snapshots',
    sa.Column('match_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('odds_snapshot_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('snapshot_type', sa.String(length=40), nullable=False),
    sa.Column('target_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('series_key', sa.String(length=64), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['odds_snapshot_id'], ['odds_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_key', 'snapshot_type', 'kickoff_at')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odds_key_snapshots')
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_odds_series')
        batch_op.drop_index('ix_odds_cutoff')

    op.drop_table('odds_snapshots')
    with op.batch_alter_table('match_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_versions_match_id'))
        batch_op.drop_index(batch_op.f('ix_match_versions_collected_at'))

    op.drop_table('match_versions')
    with op.batch_alter_table('match_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_mapping_status'))
        batch_op.drop_index(batch_op.f('ix_match_mapping_match_id'))

    op.drop_table('match_mapping')
    op.drop_table('team_identities')
    with op.batch_alter_table('team_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_aliases_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_aliases_normalized_name'))

    op.drop_table('team_aliases')
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_runs_provider'))

    op.drop_table('sync_runs')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))

    op.drop_table('refresh_tokens')
    op.drop_table('provider_matches')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_sell_date'))
        batch_op.drop_index(batch_op.f('ix_matches_kickoff_at'))

    op.drop_table('matches')
    op.drop_table('competition_identities')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('provider_states')
    with op.batch_alter_table('provider_raw_payloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_raw_payloads_provider'))
        batch_op.drop_index(batch_op.f('ix_provider_raw_payloads_payload_hash'))
        batch_op.drop_index(batch_op.f('ix_provider_raw_payloads_collected_at'))

    op.drop_table('provider_raw_payloads')
    op.drop_table('competitions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_operation'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###

